name: dash-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy=1.21
  - scipy
  - sympy
  - matplotlib
  - numba
  - voila
  - bokeh
  - nbsphinx
  - IPython
  - ipykernel
  - requests
  - pandas
  - ipympl
  - pip
  - pip:
    - nbgitpuller
    - sphinx-gallery
    - pandas
    - pydae
    - pydgrid
    - svgwrite